server {
  listen 80;
  listen [::]:80;
  server_name api.md-zgxt.com;
  client_max_body_size 25m;

  location ^~ /.well-known/acme-challenge/ {
    root /var/www/certbot;
    default_type "text/plain";
    try_files $uri =404;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 80;
  listen [::]:80;
  server_name admin.md-zgxt.com;
  client_max_body_size 25m;

  location ^~ /.well-known/acme-challenge/ {
    root /var/www/certbot;
    default_type "text/plain";
    try_files $uri =404;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 80;
  listen [::]:80;
  server_name swap.md-zgxt.com;
  client_max_body_size 25m;

  location ^~ /.well-known/acme-challenge/ {
    root /var/www/certbot;
    default_type "text/plain";
    try_files $uri =404;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name api.md-zgxt.com;
  client_max_body_size 25m;

  ssl_certificate /etc/letsencrypt/live/md-zgxt.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/md-zgxt.com/privkey.pem;
  ssl_session_timeout 1d;
  ssl_session_cache shared:RWATSSL:10m;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers off;

  location /upload/ {
    alias /var/www/rwat/upload/;
    access_log off;
    add_header Cache-Control "public, max-age=31536000";
    try_files $uri =404;
  }

  location / {
    proxy_pass http://rwat-go-server:8000;
    proxy_http_version 1.1;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_connect_timeout 300s;
    proxy_send_timeout 300s;
    proxy_read_timeout 300s;
  }
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name admin.md-zgxt.com;
  client_max_body_size 25m;

  ssl_certificate /etc/letsencrypt/live/md-zgxt.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/md-zgxt.com/privkey.pem;
  ssl_session_timeout 1d;
  ssl_session_cache shared:RWATSSL:10m;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers off;

  location / {
    proxy_pass http://rwat-admin-ui:80;
    proxy_http_version 1.1;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_connect_timeout 300s;
    proxy_send_timeout 300s;
    proxy_read_timeout 300s;
  }
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name swap.md-zgxt.com;
  client_max_body_size 25m;

  ssl_certificate /etc/letsencrypt/live/md-zgxt.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/md-zgxt.com/privkey.pem;
  ssl_session_timeout 1d;
  ssl_session_cache shared:RWATSSL:10m;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers off;

  location / {
    proxy_pass http://rwat-dex-ui:80;
    proxy_http_version 1.1;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_connect_timeout 300s;
    proxy_send_timeout 300s;
    proxy_read_timeout 300s;
  }
}
